name: ci

on:
  push:
    branches:
      - "main"

env:
  TEST_TAG: thesecureautomator/flask-app:test
  LATEST_TAG: thesecureautomator/flask-app:latest
  MONDOO_CONFIG_BASE64: ${{ secrets.MONDOO_CONFIG_BASE64 }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Security Scan
        run: |
          echo "Installing cnspec"
          bash -c "$(curl -sSL https://install.mondoo.com/sh)"
          cnspec status
          cnspec vuln docker ${{ env.TEST_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.LATEST_TAG }}



    #   - name: Login to GHCR.io
    #     uses: docker/login-action@v2
    #     with:
    #       registry: ghcr.io
    #       username: ${{ github.repository_owner }}
    #       password: ${{ secrets.GHCR_TOKEN }}

    #   - name: Build and export to Docker
    #     uses: docker/build-push-action@v3
    #     with:
    #       context: .
    #       load: true
    #       tags: |
    #         ghcr.io/${{github.repository_owner}}/${{env.APP}}:latest
    #         ghcr.io/${{github.repository_owner}}/${{env.APP}}:${{env.VERSION}}
    #       secrets:
    #         GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}

    #   - name: Build and push
    #     uses: docker/build-push-action@v3
    #     with:
    #       context: .
    #       tags: |
    #         ghcr.io/${{github.repository_owner}}/${{env.APP}}:latest
    #         ghcr.io/${{github.repository_owner}}/${{env.APP}}:${{env.VERSION}}
    #       push: ${{ github.ref == 'refs/heads/main' }}

    #   - name: Image Digest
    #     run: echo ${{ steps.docker_build.outputs.digest }}